resolver: nightly-2017-06-01
packages:
- "servant-contrib"
- "servant-client-contrib"
- "servant-server-contrib"
extra-deps:
- servant-0.11
- servant-server-0.11
- servant-client-0.11
- generics-sop-0.3.0.0
flags: {}
